# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb9c5f44eb7e11c9d7f910bb5ae09752a7e40caee7575d0de5445616d6ecf7716e503c9a3ea0f188c3173d2860c3f7fc80fd09157aa5e76176c7846e299be55

test:
  secret_key_base: 7e15ec2e855c96cd853d78bc34a9039982f3a9fb88cd256635f9a5ddde7a229f3f927bb0f41c337221373261f8fd495d59c4db1890ce63ebaee367fb0c073e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
